[build]
  # Build command (for static sites, this can be empty or a simple echo)
  command = "npm run build"
  
  # Publish directory (root directory for static HTML files)
  publish = "."
  
  # Functions directory (if you add Netlify Functions later)
  functions = "netlify/functions"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

# Redirect rules for SPA behavior
[[redirects]]
  # Handle auth callback from Supabase
  from = "/auth/callback"
  to = "/dashboard.html"
  status = 200

# Root will serve index.html automatically

[[redirects]]
  # Redirect auth to login page
  from = "/auth"
  to = "/login.html"
  status = 301

[[redirects]]
  # Handle 404s by serving home page
  from = "/*"
  to = "/home.html"
  status = 404

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache control for static assets
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.html"
  [headers.values]
    # Don't cache HTML files
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.js"
  [headers.values]
    # Cache JS files for 1 year
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    # Cache CSS files for 1 year
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (these should be set in Netlify UI for security)
# SUPABASE_URL = "your-supabase-url"
# SUPABASE_ANON_KEY = "your-supabase-anon-key"
